site_name: NGS - variant analysis

nav:
  - Home: index.md
  - Precourse preparations: precourse.md
  - Course schedule: course_schedule.md
  - Day 1:
    - Introduction: day1/introduction.md
    - Setup: day1/server_login.md
    - Reproducibility: day1/reproducibility.md
    - Read alignment - basics: day1/alignment.md
    - Read alignment - advanced: day1/alignment_advanced.md
  - Day 2:
    - Variant calling - preparation: day2/variant_calling_preparation.md
    - Variant calling: day2/variant_calling.md
    - Visualisation: day2/visualisation.md
    - Filtering & evaluation: day2/filtering_evaluation.md
    - Annotation: day2/annotation.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss

# Repository
repo_name: sib-swiss/NGS-variants-training
repo_url: https://github.com/sib-swiss/NGS-variants-training
edit_uri: edit/main/docs/

site_url: https://sib-swiss.github.io/NGS-variants-training/

markdown_extensions:
  - meta
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    default: latest
  analytics:
    provider: matomo
    base_url: https://matomo.sib.swiss/
    site_id: 220

copyright: >
  Copyright &copy; 2021-2022 SIB Swiss institute of Bioinformatics –

